/// GENERATED BY OZIBABA
import 'dart:typed_data';
import 'package:json_annotation/json_annotation.dart';

/// 
/// The service capabilities reflect optional functionality of a service. The information is static
/// and does not change during device operation. The following capabilities are available:
/// 
@JsonSerializable()
class ServiceCapabilities  {
  /// 
/// Indicates whether or not several access policies can refer to the same access point in an
/// access profile.
/// 
@JsonKey(name: 'MultipleSchedulesPerAccessPointSupported')
final bool multipleSchedulesPerAccessPointSupported;
  /// 
/// Indicates that the client is allowed to supply the token when creating access profiles. To
/// enable the use of the command SetAccessProfile, the value must be set to true.
/// 
@JsonKey(name: 'ClientSuppliedTokenSupported')
final bool clientSuppliedTokenSupported;
  ServiceCapabilities({
        required this.multipleSchedulesPerAccessPointSupported,
        required this.clientSuppliedTokenSupported,
  });
}

/// 
/// The access policy is an association of an access point and a schedule. It defines when an access
/// point can be accessed using an access profile which contains this access policy. If an access
/// profile contains several access policies specifying different schedules for the same access
/// point will result in a union of the schedules.
/// 
@JsonSerializable()
class AccessPolicy  {
  /// Reference to the schedule used by the access policy.
@JsonKey(name: 'ScheduleToken')
final ReferenceToken scheduleToken;
  /// 
/// Reference to the entity used by the rule engine, the entity type may be specified by the
/// optional EntityType field explained below but is typically an access point.
/// 
@JsonKey(name: 'Entity')
final ReferenceToken entity;
  /// 
/// Optional entity type; if missing, an access point type as defined by the ONVIF Access
/// Control Service Specification should be assumed. This can also be represented by the
/// QName value“tac:AccessPoint” where tac is the namespace of ONVIF Access Control
/// Service Specification. This field is provided for future extensions; it will allow an
/// access policy beingextended to cover entity types other than access points as well.
/// 
@JsonKey(name: 'EntityType')
final String? entityType;
  @JsonKey(name: 'Extension')
final AccessPolicyExtension? extension_;
  AccessPolicy({
        required this.scheduleToken,
        required this.entity,
        this.entityType,
        this.extension_,
  });
}

class AccessPolicyExtension {}
/// 
/// The AccessProfileInfo structure contains basic information about an access profile. The device
/// shall provide the following fields for each access profile instance.
/// 

/// 
/// The access profile structure contains information about the collection of access policies. The
/// device shall include all properties of the AccessProfileInfo structure and also a list of access
/// policies.
/// 
class AccessProfile {}
class AccessProfileExtension {}
class GetServiceCapabilities {}
@JsonSerializable()
class GetServiceCapabilitiesResponse  {
  /// The capability response message contains the requested access rules
/// service capabilities using a hierarchical XML capability structure.
/// 
@JsonKey(name: 'Capabilities')
final ServiceCapabilities capabilities;
  GetServiceCapabilitiesResponse({
        required this.capabilities,
  });
}

@JsonSerializable()
class GetAccessProfileInfo  {
  /// Tokens of AccessProfileInfo items to get.
@JsonKey(name: 'Token')
final ReferenceToken token;
  GetAccessProfileInfo({
        required this.token,
  });
}

@JsonSerializable()
class GetAccessProfileInfoResponse  {
  /// List of AccessProfileInfo items.
@JsonKey(name: 'AccessProfileInfo')
final AccessProfileInfo? accessProfileInfo;
  GetAccessProfileInfoResponse({
        this.accessProfileInfo,
  });
}

@JsonSerializable()
class GetAccessProfileInfoList  {
  /// Maximum number of entries to return. If not specified, less than one
/// or higher than what the device supports, the number of items is determined by the
/// device.
/// 
@JsonKey(name: 'Limit')
final int? limit;
  /// Start returning entries from this start reference. If not specified,
/// entries shall start from the beginning of the dataset.
/// 
@JsonKey(name: 'StartReference')
final String? startReference;
  GetAccessProfileInfoList({
        this.limit,
        this.startReference,
  });
}

@JsonSerializable()
class GetAccessProfileInfoListResponse  {
  /// StartReference to use in next call to get the following items. If
/// absent, no more items to get.
/// 
@JsonKey(name: 'NextStartReference')
final String? nextStartReference;
  /// List of AccessProfileInfo items.
@JsonKey(name: 'AccessProfileInfo')
final AccessProfileInfo? accessProfileInfo;
  GetAccessProfileInfoListResponse({
        this.nextStartReference,
        this.accessProfileInfo,
  });
}

@JsonSerializable()
class GetAccessProfiles  {
  /// Tokens of AccessProfile items to get.
@JsonKey(name: 'Token')
final ReferenceToken token;
  GetAccessProfiles({
        required this.token,
  });
}

@JsonSerializable()
class GetAccessProfilesResponse  {
  /// List of Access Profile items.
@JsonKey(name: 'AccessProfile')
final AccessProfile? accessProfile;
  GetAccessProfilesResponse({
        this.accessProfile,
  });
}

@JsonSerializable()
class GetAccessProfileList  {
  /// Maximum number of entries to return. If not specified, less than one
/// or higher than what the device supports, the number of items is determined by the
/// device.
/// 
@JsonKey(name: 'Limit')
final int? limit;
  /// Start returning entries from this start reference. If not specified,
/// entries shall start from the beginning of the dataset.
/// 
@JsonKey(name: 'StartReference')
final String? startReference;
  GetAccessProfileList({
        this.limit,
        this.startReference,
  });
}

@JsonSerializable()
class GetAccessProfileListResponse  {
  /// StartReference to use in next call to get the following items. If
/// absent, no more items to get.
/// 
@JsonKey(name: 'NextStartReference')
final String? nextStartReference;
  /// List of Access Profile items.
@JsonKey(name: 'AccessProfile')
final AccessProfile? accessProfile;
  GetAccessProfileListResponse({
        this.nextStartReference,
        this.accessProfile,
  });
}

@JsonSerializable()
class CreateAccessProfile  {
  /// The AccessProfile to create.
@JsonKey(name: 'AccessProfile')
final AccessProfile accessProfile;
  CreateAccessProfile({
        required this.accessProfile,
  });
}

@JsonSerializable()
class CreateAccessProfileResponse  {
  /// The Token of created AccessProfile.
@JsonKey(name: 'Token')
final ReferenceToken token;
  CreateAccessProfileResponse({
        required this.token,
  });
}

@JsonSerializable()
class ModifyAccessProfile  {
  /// The details of Access Profile
@JsonKey(name: 'AccessProfile')
final AccessProfile accessProfile;
  ModifyAccessProfile({
        required this.accessProfile,
  });
}

class ModifyAccessProfileResponse {}
@JsonSerializable()
class SetAccessProfile  {
  /// The AccessProfile item to create or modify
@JsonKey(name: 'AccessProfile')
final AccessProfile accessProfile;
  SetAccessProfile({
        required this.accessProfile,
  });
}

class SetAccessProfileResponse {}
@JsonSerializable()
class DeleteAccessProfile  {
  /// The token of the access profile to delete.
@JsonKey(name: 'Token')
final ReferenceToken token;
  DeleteAccessProfile({
        required this.token,
  });
}

class DeleteAccessProfileResponse {}
