import '../onvif/onvif.dart';
/// GENERATED BY OZIBABA
import 'dart:typed_data';
import 'package:json_annotation/json_annotation.dart';

@JsonSerializable()
class MotionRegionConfigOptions  {
  /// 
/// The total number of Motion Region Detector rules that can be created on the device.
/// This element is deprecated. maxInstances in the GetSupportedRules shall be used instead.
/// 
@JsonKey(name: 'MaxRegions')
final int? maxRegions;
  /// 
/// True if the device supports disarming a Motion Region Detector rule.
/// 
@JsonKey(name: 'DisarmSupport')
final bool? disarmSupport;
  /// 
/// True if the device supports defining a region using a Polygon instead of a rectangle.
/// The rectangle points are still passed using a Polygon element if the device does not support polygon regions.
/// In this case, the points provided in the Polygon element shall represent a rectangle.
/// 
@JsonKey(name: 'PolygonSupport')
final bool? polygonSupport;
  /// 
/// For devices that support Polygons with limitations on the number of sides, 
/// provides the minimum and maximum number of sides that can be defined in the 
/// Polygon.
/// 
@JsonKey(name: 'PolygonLimits')
final IntRange? polygonLimits;
  /// 
/// Indicates the device can only support one sensitivity level for all defines 
/// motion detection regions. Changing the sensitivity for one region would be 
/// applied to all regions.
/// 
@JsonKey(name: 'SingleSensitivitySupport')
final bool? singleSensitivitySupport;
  /// 
/// True if the device will include the Name of the Rule to indicate the region 
/// that motion was detected in.
/// 
@JsonKey(name: 'RuleNotification')
final bool? ruleNotification;
  /// 
/// Indicates the support for PTZ preset based motion detection, if supported Preset token can be associated with a motion region.
/// 
@JsonKey(name: 'PTZPresetMotionSupport')
final bool pTZPresetMotionSupport;
  MotionRegionConfigOptions({
        this.maxRegions,
        this.disarmSupport,
        this.polygonSupport,
        this.polygonLimits,
        this.singleSensitivitySupport,
        this.ruleNotification,
        required this.pTZPresetMotionSupport,
  });
}

@JsonSerializable()
class MotionRegionConfig  {
  /// 
/// Preset position associated with the motion region defined by Polygon.
/// 
@JsonKey(name: 'PresetToken')
final ReferenceToken? presetToken;
  MotionRegionConfig({
        this.presetToken,
  });
}

