/// GENERATED BY OZIBABA
import 'dart:typed_data';
import 'package:json_annotation/json_annotation.dart';

import 'package:dart_wsdl_gen/onvif_gen/xsd_dart/lib.dart';
class GetServiceCapabilities {}
@JsonSerializable()
class GetServiceCapabilitiesResponse  {
  /// The capabilities for the replay service is returned in the Capabilities element.
@JsonKey(name: 'Capabilities')
final Capabilities capabilities;
  GetServiceCapabilitiesResponse({
        required this.capabilities,
  });
}

@JsonSerializable()
class Capabilities  {
  /// Indicator that the Device supports reverse playback as defined in the ONVIF Streaming Specification. 
@JsonKey(name: 'ReversePlayback')
final bool reversePlayback;
  /// The list contains two elements defining the minimum and maximum valid values supported as session timeout in seconds. 
@JsonKey(name: 'SessionTimeoutRange')
final FloatAttrList sessionTimeoutRange;
  /// Indicates support for RTP/RTSP/TCP.
@JsonKey(name: 'RTP_RTSP_TCP')
final bool rTP_RTSP_TCP;
  /// If playback streaming over WebSocket is supported, this shall return the RTSP WebSocket URI as described in Streaming Specification Section 5.1.1.5.
@JsonKey(name: 'RTSPWebSocketUri')
final String rTSPWebSocketUri;
  Capabilities({
        required this.reversePlayback,
        required this.sessionTimeoutRange,
        required this.rTP_RTSP_TCP,
        required this.rTSPWebSocketUri,
  });
}

@JsonSerializable()
class GetReplayUri  {
  /// Specifies the connection parameters to be used for the stream. The URI that is returned may depend on these parameters.
@JsonKey(name: 'StreamSetup')
final StreamSetup streamSetup;
  /// The identifier of the recording to be streamed.
@JsonKey(name: 'RecordingToken')
final ReferenceToken recordingToken;
  GetReplayUri({
        required this.streamSetup,
        required this.recordingToken,
  });
}

@JsonSerializable()
class GetReplayUriResponse  {
  /// The URI to which the client should connect in order to stream the recording.
@JsonKey(name: 'Uri')
final String uri;
  GetReplayUriResponse({
        required this.uri,
  });
}

@JsonSerializable()
class SetReplayConfiguration  {
  /// Description of the new replay configuration parameters.
@JsonKey(name: 'Configuration')
final ReplayConfiguration configuration;
  SetReplayConfiguration({
        required this.configuration,
  });
}

class SetReplayConfigurationResponse {}
class GetReplayConfiguration {}
@JsonSerializable()
class GetReplayConfigurationResponse  {
  /// The current replay configuration parameters.
@JsonKey(name: 'Configuration')
final ReplayConfiguration configuration;
  GetReplayConfigurationResponse({
        required this.configuration,
  });
}

