/// GENERATED BY OZIBABA
import 'dart:typed_data';
import 'package:json_annotation/json_annotation.dart';

class Documentation {}
@JsonSerializable()
class ExtensibleDocumented  {
  @JsonKey(name: 'documentation')
final Documentation? documentation;
  ExtensibleDocumented({
        this.documentation,
  });
}

@JsonSerializable()
class QueryExpressionType  {
  @JsonKey(name: 'Dialect')
final String dialect;
  QueryExpressionType({
        required this.dialect,
  });
}

class TopicNamespaceType {}
class TopicNamespace {}
class TopicType {}
class TopicSetType {}
@JsonSerializable()
class FullTopicExpression  {
  @JsonKey(name: 'val')
final String val;
  FullTopicExpression({
        required this.val,
  });
}

@JsonSerializable()
class ConcreteTopicExpression  {
  @JsonKey(name: 'val')
final String val;
  ConcreteTopicExpression({
        required this.val,
  });
}

@JsonSerializable()
class SimpleTopicExpression  {
  @JsonKey(name: 'val')
final String val;
  SimpleTopicExpression({
        required this.val,
  });
}

